services:
  openclaw:
    image: ghcr.io/openclaw/openclaw:latest
    container_name: openclaw
    restart: always
    volumes:
      - /mnt/f/Docker/openclaw/config:/home/node/.openclaw
      - /var/run/docker.sock:/var/run/docker.sock
      - openclaw-extensions:/home/node/.openclaw/extensions
      - /mnt/e/Obsidian_Repository/Gyw_Obsidian_Repository:/home/node/obsidian-vault
      - /mnt/f/Obsidian/vault:/home/node/obsidian-vault-template
      - /mnt/f/Docker/openclaw/ms-todo-config:/home/node/.config/microsoft-todo
    environment:
      - OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_TOKEN}
    env_file:
      - .env
    ports:
      - "127.0.0.1:18789:18789"
    networks:
      - proxy

volumes:
  openclaw-extensions:

networks:
  proxy:
    external: true
